export const COFFEE_BRANDS_NON_CLASS_BASED = 'COFFEE_BRANDS_NON_CLASS_BASED';
export const COFFEE_BRANDS_BASIC_FACTORY = 'COFFEE_BRANDS_BASIC_FACTORY';
export const COFFEE_BRANDS_FACTORY_CLASS = 'COFFEE_BRANDS_FACTORY_CLASS';
export const COFFEE_BRANDS_ASYNC_FACTORY = 'COFFEE_BRANDS_ASYNC_FACTORY';
